tts: transformer
tts_conf:
  loss_type: "ASR"


##########################################################
#                OTHER TRAINING SETTING                  #
##########################################################
num_iters_per_epoch: 10   # number of iterations per epoch
max_epoch: 2              # number of epochs
log_interval: 1          # log interval in iterations
