tts: transformer
tts_conf:
  loss_type: "ASR"  # Technically self-supervised

##########################################################
#            OPTIMIZER & SCHEDULER SETTING               #
##########################################################
optim: adam             # optimizer type
optim_conf:             # keyword arguments for selected optimizer
    lr: 1.0             # learning rate
scheduler: noamlr       # scheduler type
scheduler_conf:         # keyword arguments for selected scheduler
    model_size: 512     # model size, a.k.a., attention dimenstion
    warmup_steps: 8000  # the number of warmup steps

##########################################################
#                OTHER TRAINING SETTING                  #
##########################################################
num_iters_per_epoch: 1000   # number of iterations per epoch
max_epoch: 2 # 200          # number of epochs
grad_clip: 1.0              # gradient clipping norm
grad_noise: false           # whether to use gradient noise injection
accum_grad: 2               # gradient accumulation
batch_bins: 9000000         # batch bins (for feats_type=raw, *= n_shift / n_mels)
batch_type: numel           # how to make batch
sort_in_batch: descending   # how to sort data in making batch
sort_batch: descending      # how to sort created batches
num_workers: 1              # number of workers of data loader
train_dtype: float32        # dtype in training
log_interval: 100           # log interval in iterations
keep_nbest_models: 5        # number of models to keep
num_att_plot: 3             # number of attention figures to be saved in every check
seed: 0                     # random seed number
best_model_criterion:
-   - valid
    - loss
    - min
-   - train
    - loss
    - min
